tap "homebrew/bundle"

cask_args appdir: "~/Applications", require_sha: true

brew "ansible"
brew "bat"
brew "php"
brew "composer"
brew "coreutils"
brew "ctop"
brew "gcc"
brew "gh"
brew "git"
brew "go-task"
brew "ios-deploy"
brew "make"
brew "mkcert"
brew "neovim"
brew "pkgconf"
brew "pyenv"
brew "python-setuptools"
brew "ruby-build"
brew "rbenv"
brew "stow"
brew "unzip"
brew "watchman"
brew "wget"
brew "yq"

cask "1password-cli"
cask "figma"
cask "ngrok"
cask "orbstack"
cask "slack"
cask "visual-studio-code"
cask "warp"
cask "zulu@17"
