#!/bin/zsh

sudo mkdir -p /usr/local/bin

if ! command -v brew > /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle install --no-lock

stow --dotfiles -t $HOME home

if [ -z "${NVM_DIR}" ]; then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
fi
