#!/usr/bin/env zsh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

yabai -m config                                 \
    external_bar                 all:32:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.25           \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.25           \
    active_window_opacity        1.0            \
    normal_window_opacity        0.75           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  32             \
    bottom_padding               32             \
    left_padding                 16             \
    right_padding                16             \
    window_gap                   16             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

#
# setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 7)'); do
  yabai -m space --destroy 8
done

function setup_space() {
  local idx="$1"
  local space

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$idx"
}

setup_space "$i"

# move some apps automatically to specific spaces
yabai -m space 2 --label "2 Slack"
yabai -m rule --add app="^Slack$" space=2
yabai -m space 3 --label "3 Browser"
yabai -m rule --add app="^Arc$" space=^3
yabai -m space 4 --label "4 Dev"
yabai -m rule --add app="^Code$" space=^4
yabai -m rule --add app="^Simulator$" space=^4
yabai -m rule --add app="^Xcode$" space=^4
yabai -m space 5 --label "5 Terminal"
yabai -m rule --add app="^iTerm2*" space=^5
yabai -m space 6 --label "6 Spotify"
yabai -m rule --add app="^Spotify$" space=^6

echo "yabai configuration loaded.."

