system "zsh -l -c \"brew bundle --file ~/.homebrew/Brewfile.nvim\""
[
  "core",
  "dev",
  "nvim",
  "cask",
].each do |name|
  system "zsh -l -c \"brew bundle --file ~/.homebrew/Brewfile.#{name}\""
end