tap "homebrew/bundle"

cask_args appdir: "~/Applications", require_sha: true

cask "1password-cli"
cask "dbeaver-community"
cask "font-hack-nerd-font"
cask "ngrok"
cask "orbstack"
cask "slack"
cask "visual-studio-code"
cask "zulu@17"
